require("config.options")
require("config.usercommands")
require("config.keymaps")
require("config.autocmds")
-- require("config.lazy")
-- require("config.neovide")
require("config.plugins")
vim.cmd("colorscheme rose-pine-dawn")
