vim.api.nvim_set_keymap('n', '<leader>mw', "<Plug>VimwikiIndex", { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>mt', "<Plug>VimwikiTabIndex", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>ms', "<Plug>VimwikiUISelect", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>mi', "<Plug>VimwikiDiaryIndex", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>md', "<Plug>VimwikiDeleteFile", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>mr', "<Plug>VimwikiRenameFile", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>mn', "<Plug>VimwikiGoto", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>mc', "<Plug>VimwikiColorize", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>m<leader>w', "<Plug>VimwikiMakeDiaryNote", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>m<leader>t', "<Plug>VimwikiTabMakeDiaryNote", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>m<leader>y', "<Plug>VimwikiMakeYesterdayDiaryNote", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>m<leader>m', "<Plug>VimwikiMakeTomorrowDiaryNote", { silent = true })
vim.api.nvim_set_keymap('n', '<leader>m<leader>i', "<Plug>VimwwikiDiaryGenerateLinks", { silent = true })
